apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-sample
  namespace: openshift-gitops
spec:
  sourceNamespaces:
  - openshift-gitops
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
  - path: charts/hello-world
    repoURL: 'https://github.com/harshil-codes/sample-helm'
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/values
  - repoURL: 'https://github.com/harshil-codes/sample-helm-dep'
    targetRevision: main
    ref: values
  project: default

