apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-app
  namespace: openshift-gitops
spec:
  sourceNamespaces:
  - openshift-gitops
  destination:
    namespace: httpd-app
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: httpd-app
    repoURL: 'https://github.com/harshil-codes/example-argo-app'
    targetRevision: HEAD

